language: rust
rust:
  - nightly
  - beta
  - 1.8.0
  - 1.9.0
before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
script:
  - |
      cargo test &&
      cargo test --features watch &&
      travis-cargo --only nightly test -- --no-default-features
