[package]

name = "handlebars-iron"
version = "0.8.4"
authors = ["Ning Sun <sunng@about.me>"]
description = "Handlebars templating middleware for Iron."
license = "MIT"
keywords = ["handlebars", "templating", "web", "webdev", "iron"]
homepage = "https://github.com/sunng87/handlebars-iron"
repository = "https://github.com/sunng87/handlebars-iron"
documentation = "http://sunng.info/handlebars-iron/"
readme = "README.md"

[dependencies]

iron = "^0.2.0"
handlebars = "^0.11.1"
rustc-serialize = "^0.3.15"
plugin = "^0.2.6"
notify = { version = "^2.3", optional = true }
log = "^0.3"
walkdir = "^0.1"

[features]
default = []
watch = ["notify"]

[dev-dependencies]
env_logger = "*"
