[package]

name = "handlebars-iron"
version = "0.9.1"
authors = ["Ning Sun <sunng@about.me>"]
description = "Handlebars templating middleware for Iron."
license = "MIT"
keywords = ["handlebars", "templating", "web", "webdev", "iron"]
homepage = "https://github.com/sunng87/handlebars-iron"
repository = "https://github.com/sunng87/handlebars-iron"
documentation = "http://sunng.info/handlebars-iron/"
readme = "README.md"

[dependencies]

iron = { version = "^0.2.0", default-features = false }
handlebars = "^0.11.1"
rustc-serialize = "^0.3.15"
plugin = "^0.2.6"
notify = { git = "https://github.com/passcod/rsnotify", branch = "use-walkdir", optional = true }
log = "^0.3"
walkdir = "^0.1"

[features]
default = []
watch = ["notify"]

[dev-dependencies]
env_logger = "*"
